CREATE DATABASE  IF NOT EXISTS `apidatabase` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `apidatabase`;
-- MySQL dump 10.13  Distrib 8.0.18, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: apidatabase
-- ------------------------------------------------------
-- Server version	8.0.18

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `listings`
--

DROP TABLE IF EXISTS `listings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `listings` (
  `id` int(11) DEFAULT NULL,
  `category` longtext,
  `street_num` longtext,
  `unit_num` longtext,
  `street_name` longtext,
  `suburb` longtext,
  `postcode` int(11) DEFAULT NULL,
  `price` longtext,
  `numericPrice` longtext,
  `bed` int(11) DEFAULT NULL,
  `bath` int(11) DEFAULT NULL,
  `car` longtext,
  `sqm` longtext,
  `property_description` longtext,
  `features` longtext,
  `property_type` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `listings`
--

LOCK TABLES `listings` WRITE;
/*!40000 ALTER TABLE `listings` DISABLE KEYS */;
INSERT INTO `listings` VALUES (13687260,'rent','17/90',NULL,'Brooks Street','Cooks Hill',2300,'$450','450',2,1,'1',NULL,'Conveniently located just a short walk to the Darby Street restaurant precinct and Bar Beach is this unit perfect for inner city living.\r\nProperty is not suitable for pets.\r\n\r\n\r\n- Spacious open plan living room flows to large entertaining balcony\r\n\r\n- Neat and tidy kitchen featuring ample storage space\r\n\r\n- To light filled bedrooms with built in wardrobes\r\n\r\n- Spacious bathroom with shower and bath\r\n\r\n- Under cover secure parking space for one car\r\n\r\n- Walk to shops, bars, restaurants and cafs and beach\r\n\r\n- Quiet complex, visitor parking spots, low maintenance gardens\r\n\r\n- Close to public transport routes',NULL,NULL);
INSERT INTO `listings` VALUES (13649880,'rent','1','59','Murray Street','Pyrmont',2009,'DEPOSIT TAKEN $1,200 per week','$1200',3,3,'2','208','A rare find in this tranquil 208 square metre courtyard apartment which is located  in a premium harbourside community. A major drawcard location at the gateway to Darling Harbour, The Star, Chinatown and Sydney\'s CBD. Across Darling Harbour\'s renowned waterway sits Barangaroo, Australia\'s leading international development.\r\n\r\nApartment Features:\r\n\r\n-	Easy living, one level low maintenance 3 bedroom apartment\r\n-	All rooms open up onto gorgeous 50sqm courtyard.\r\n-	Courtyard offers built in seating, BBQ area perfect for entertaining \r\n-	King-size master bedroom with walk-through mirrored robes\r\n-	Stone ensuite bathroom with bath \r\n-	Gourmet kitchen with easy-care granite benchtops \r\n-       Smeg gas cooktop, electric wall oven, microwave and dishwasher\r\n-	Generous lounge and separate dining area with built-in cupboards \r\n-	A queen-size second bedroom with mirrored robes\r\n-       Second stone-tiled bathroom, an additional guest bathroom\r\n-	Single-size third bedroom with mirrored robes and built-in desk\r\n-	Ducted air-conditioning throughout\r\n-	2 secure side-by side car spaces, with visitor parking also available\r\n\r\nThe features in the Gateway complex include a heated indoor pool, sauna, gym, and secure bike storage room. Extremely well-run building, video security intercom, building manager onsite  Cable or Satellite,  Broadband internet access and Secure Parking.',NULL,'apartmentUnitFlat');
INSERT INTO `listings` VALUES (2014173064,'sale','187-191',NULL,'Michael Street','Jesmond',2299,'$370,000  - $399,000','$370000$399000',1,1,'1',NULL,'Si Marco Apartments is a collaboration between multi-award winning Kingston Building Australia and renowned Newcastle Architects SDA, this purpose-built boutique complex of 24 apartments has all the hallmarks of a stylish contemporary lifestyle. Set in the heart of Jesmond, it offers designer living in a central location.\r\n\r\n\r\n- A selection of one bedroom apartments over two levels\r\n\r\n- Perfect for owner/occupiers or equally for savvy investors\r\n\r\n- Each apartment features open plan living and outdoor space\r\n\r\n- Features generous proportions and stylish, quality finishes\r\n\r\n- Kitchens feature European styled appliances and stone benchtops\r\n\r\n- Split system air conditioning to each apartment\r\n\r\n- Single security car parking plus a storage cage for each\r\n\r\n- 100m to Stockland Jesmond\'s array of shops and cafes\r\n\r\n- 1km to University, 3km to John Hunter Hospital, 9km CBD\r\n\r\n- Moments to M1 freeway and Hunter Expressway',NULL,NULL);
INSERT INTO `listings` VALUES (2015803893,'sale','13',NULL,'Casson Avenue','Eleebana',2282,'$1,620,000  - $1,780,000','$1620000$1780000',4,2,'3','10000','Surrounded by 1 hectare of lush lawns and thriving greenery, this exquisite family retreat is positioned in one of Eleebanas most prestigious locations. Embraced by glorious park-like grounds offering a relaxed, country lifestyle with a resort-like ambience.\r\n\r\n\r\n- Instantly striking with its overall sense of serene tranquillity \r\n\r\n- Being offered to the market for the first time in 36 years\r\n\r\n- Showcasing an open plan design and an architectural feel \r\n\r\n- Beautifully/lovingly maintained across every inch of this home\r\n\r\n- Stylishly renovated interiors with timber vaulted ceilings \r\n\r\n- Freshly painted throughout with multiple living spaces \r\n\r\n- Renovated kitchen, with stone benchtop and dishwasher\r\n\r\n- Master bedroom with ensuite, walk-in robe and ceiling fans\r\n\r\n- Spacious rumpus/teenage retreat above large triple garage\r\n\r\n- Moments to the foreshore/Warners Bay shopping/dining',NULL,NULL);
INSERT INTO `listings` VALUES (2014794263,'sale','22',NULL,'Rembrandt Drive','Merewether Heights',2291,'$790,000  - $840,000','$790000$840000',4,2,'2','700','This nature\'s wonderland oasis enjoys a layout over three levels. Set on a north to rear, sloping site, but with a level backyard ideal for kids to explore and enjoy. Peacefully set in a quiet street of one of Newcastles finest suburbs. \r\n\r\n\r\n- Weatherboard home in with tranquil leafy outlook\r\n\r\n- Split level living with hardwood floors throughout\r\n\r\n- Timber verandah off both loungerooms, top verandah enclosed\r\n\r\n- Well appointed kitchen with breakfast bar\r\n\r\n- Upstairs area with lounge room, verandah and study\r\n\r\n- Three bedrooms with carpet, all with built-ins\r\n\r\n- Main bedroom with floorboards and ensuite\r\n\r\n- Main bathroom has separate bath and shower, separate w/c\r\n\r\n- Split system air conditioning, double lock-up garage\r\n\r\n- Walk to school, minutes to The Junction and Merewether coastline',NULL,NULL);
INSERT INTO `listings` VALUES (2015837750,'sale','122',NULL,'Victoria Street','Adamstown',2289,'Price on request',NULL,4,2,'2',NULL,'Ideal single level layout with a north facing backyard, this brand new master built home showcases a highly flexible layout ideally suited to contemporary family living. It\'s set over a family-friendly flat block, within walking distance to shops, transport, schools and the Fernleigh Track.\r\n\r\n\r\n- Single level layout reveals separate living zones for flexibility\r\n\r\n- Undercover alfresco entertaining area with natural gas point\r\n\r\n- Flat family friendly north facing yard\r\n\r\n- Stone kitchen with butlers pantry, chefs oven and gas cooktop\r\n\r\n- Four versatile bedrooms plus home office or potential for fifth room\r\n\r\n- Deluxe master bed graced with ensuite and walk-in wardrobe\r\n\r\n- Ducted Daikin air conditioning and natural gas points throughout\r\n\r\n- \'Master built\' brand new single level home\r\n\r\n- Automatic double garage with internal access\r\n\r\n- Minutes from local beaches, shops, schools and the Fernleigh track',NULL,NULL);
INSERT INTO `listings` VALUES (13709269,'rent','4/46',NULL,'Sandgate Road','Wallsend',2287,'$450','450',3,2,'1',NULL,'This near new three bedroom townhouse is in an ideal location and is sure to impress. Offering three spacious bedrooms, two bathrooms and single lock up garage. Pets may be considered upon application.\r\n\r\n\r\n- Large open plan kitchen/living and dining space \r\n\r\n- Three bedrooms all with built in robes and ceiling fans\r\n\r\n- Main bedroom with ensuite, third toilet downstairs\r\n\r\n- Crisp colour palette throughout, split system air conditioning\r\n\r\n- Close proximity to all amenities, shops and university \r\n\r\n- Low maintenance courtyard, automatic single garage\r\n\r\n- One form applications not accepted',NULL,NULL);
INSERT INTO `listings` VALUES (2015676262,'sale','39',NULL,'Cleveland Street','Cameron Park',2285,'Price on request',NULL,0,0,NULL,NULL,'Be inspired to build your new dream home or develop on this huge block of 3,010sqm, capturing a beautiful outlook to natural bushland and mountains. This rare flat block is positioned close to Edgeworth shops, public transport and schools.\r\n\r\n\r\n- Seize this incredible opportunity to design the family dream\r\n\r\n- Rare 3,010sqm level development site\r\n\r\n- This residential estate has all the infrastructure in place\r\n\r\n- Beautiful level block enjoys natures views and cool breezes\r\n\r\n- Take advantage of a perfectly oriented north facing aspect\r\n\r\n- Highly sought-after location for the growing modern family\r\n\r\n- Conveniently located near Pacific Motorway leading to Sydney\r\n\r\n- Parks, playgrounds and shops open, with transport nearby\r\n\r\n- Enjoy the space and proximity, close to Stockland Glendale\r\n\r\n- Potential development site (STCA)',NULL,NULL);
INSERT INTO `listings` VALUES (13669770,'rent','7A',NULL,'King Street','Adamstown',2289,'$550','550',3,2,'1',NULL,'Offering plenty of room for an active family, this beautifully presented home offers generous proportions, a user-friendly layout and light filled interiors. Located just minutes to local shops, schools and a short drive to the beach.\r\n\r\n\r\n- Three bedrooms, two fitted with built-in wardrobes\r\n\r\n- Ensuite to main bedroom, fully carpeted bedrooms\r\n\r\n- Spacious combined living and dining with floating timber floors \r\n\r\n- Kitchen with gas cooking and dishwasher, CaesarStone benchtops\r\n\r\n- Modern bathroom, floor-to-ceiling tiles, air conditioned\r\n\r\n- Single garage, remote entry and internal access \r\n\r\n- Low maintenance rear yard, small grassed area\r\n\r\n- Sunny deck with direct access from the living area \r\n\r\n- Short drive to Newcastle CBD, local shops and parks \r\n\r\n- Pets considered on application',NULL,NULL);
INSERT INTO `listings` VALUES (13701997,'rent','14',NULL,'Linwood Street','Maryville',2293,'$550','550',3,2,'1',NULL,'An appealing home provides relaxed living in a peaceful waterside location. It\'s positioned metres away from walkways, while handy to cafs, restaurants and Newcastle Interchange Station. This home is certainly for a professional couple or singles looking for a convenient location for a easy care, low maintenance living lifestyle.\r\n\r\n\r\n- Open plan layout with fresh paint and new carpets throughout\r\n\r\n- Undercover entertaining area, low maintenance gardens\r\n\r\n- Kitchen is well appointed a with 900mm gas cooktop and storage\r\n\r\n- Three bedrooms all feature wardrobes, neutral colour palate\r\n\r\n- Master bedroom reveals walk-in, ensuite and private balcony\r\n\r\n- Bathroom includes bath and shower recess\r\n\r\n- Internal laundry plus additional w/c off kitchen\r\n\r\n- Gas bayonets for heating, single lock-up garage at the rear\r\n\r\n- Close proximity to Marketown Shopping Centre and beaches\r\n\r\n- Central to local parks, minutes to Newcastle CBD and museum',NULL,NULL);
INSERT INTO `listings` VALUES (2015809538,'sale','126','3','Tyrrell Street','The Hill',2300,'$800,000  - $880,000','$800000$880000',3,2,'2',NULL,'Perfectly positioned overlooking Civic park and offering the ultimate in city living, this three bedroom townhouse style apartment has ultra-stylish and spacious interiors and provides instant access to the popular shopping, caf and dining mecca of Darby Street \r\n\r\n\r\n- An exceptional urban setting in a tightly-held block\r\n\r\n- Large open plan living, dining, kitchen and study space\r\n\r\n- Spacious contemporary kitchen with dishwasher, stone bench\r\n\r\n- Master bedroom with park views, walk-in wardrobe, ensuite \r\n\r\n- Large private balcony overlooking Civic Park and Darby Street \r\n\r\n- Ducted air conditioning, built-in robes, internal laundry\r\n\r\n- Additional powder room on the main entrance/living level \r\n\r\n- Double garage with auto remote door and internal access\r\n\r\n- 50m walk to the vibrant village eateries on Darby Street\r\n\r\n- Moments to beaches, Newcastle City, Honeysuckle foreshore\r\n\r\n\r\n\r\nStrata levies $1,002pq',NULL,NULL);
INSERT INTO `listings` VALUES (13678801,'rent','7',NULL,'Heddon Street','Kurri Kurri',2327,'$395','395',3,1,'1',NULL,'This substantial well presented family home is only a stones throw from Kurri Kurri High School, access to Hunter Expressway and just under twenty minutes from Stockland Greenhills. The properties convenient location provides effortless living which is suited to a professional couple or the growing family. Pets may be considered upon application.\r\n\r\n\r\n- Family friendly neighborhood, fenced child friendly backyard \r\n\r\n- Spacious light filled interiors with neutral colour tones throughout\r\n\r\n- Lounge has adjacent courtyard for effortless indoor outdoor living\r\n\r\n- Spacious kitchen with ample storage, new oven and cooktop\r\n\r\n- Three spacious bedrooms all with built in wardrobes\r\n\r\n- Informal and formal dining, ducted air conditioning throughout\r\n\r\n- Three way family bathroom, plenty of storage, walk in pantry\r\n\r\n- Large enclosed pergola overlooks manicured low maintenance gardens\r\n\r\n- Two sheds for storage, single carport, plenty of off street parking',NULL,NULL);
INSERT INTO `listings` VALUES (2015814410,'sale','122',NULL,'Lockyer Street','Adamstown',2289,'$685,000  - $735,000','$685000$735000',3,1,'1',NULL,'Blending the charm of yesteryear with its Art Deco features. Featuring polished floorboards, modern kitchen and natural gas points. The lounge room flows out to an ideal covered entertaining area, high ceilings, generous bedrooms and more.\r\n\r\n\r\n- Single carport with additional storage shed\r\n\r\n- Open plan living/kitchen/dining flowing to outdoor entertaining\r\n\r\n- Privately fenced flat front yard\r\n\r\n- Bedrooms with fans and built-in robes, natural gas points\r\n\r\n- Modern kitchen with gas cooktop\r\n\r\n- Polished timber boards with split system air con\r\n\r\n- Timber windows, high ceilings and Art Deco features\r\n\r\n- North to south aspect on a flat block\r\n\r\n- Located in one of Adamstowns most sought-after streets\r\n\r\n- Short stroll to Shops, local cafs, schools and parks',NULL,NULL);
INSERT INTO `listings` VALUES (13342912,'rent','38',NULL,'Hickey Street','Cessnock',2325,'$280','280',1,1,NULL,NULL,'Over 55\'s units available in Cessnock that are conventionally planned and equipped for low maintenance living with the convenience of having access to the community sitting area and library. A chef available for lunches at a small cost. Laundry room with amenities is available to use free of charge. These units are perfectly positioned in a quite area of town with access to daily public transport. Pets may be considered upon application.\r\n\r\n\r\n\r\n- Kitchen with bar fridge and microwave included\r\n\r\n- Open plan living area\r\n\r\n- Bedroom with reverse cycle air conditioning \r\n\r\n- Combined bathroom and laundry fitted for wheelchair access\r\n\r\n- Solar panels installed for affordable living expenses \r\n\r\n- Water is included with weekly rent\r\n\r\n- Private inspections available daily on request, phone 0428 113 108',NULL,NULL);
INSERT INTO `listings` VALUES (12633242,'rent','24','2','Druary','Wallsend',2287,'$395','$395',2,1,'1',NULL,'This 2 bedroom unit set in a small complex of 3 units. This property has a full bathroom with separate toilet. Both bedrooms have built-inns and the garage has an auto door plus internal access. the easy care court yard is ideal for a BBQ or entertaining a small group. \r\npublic transport is just up the street. \r\nNO PETS ALLOWED',NULL,'duplex');
INSERT INTO `listings` VALUES (2015139608,'sale','23','705','Ravenshaw Street','Newcastle West',2302,'$920,000  - $990,000','$920000$990000',3,2,'2',NULL,'Admire the stunning view from almost every room with a combination of city, harbour, private sky garden and eastern coastal views. Enjoy city convenience in the immaculate Spire building, immediately above Marketown and only moments to cafs, restaurants and transport.\r\n\r\n\r\n- Generous sun drenched living with large open plan design \r\n\r\n- Serene outdoor parkland, exclusively for residents use\r\n\r\n- Impressive floor-to-ceiling windows maximising natural light\r\n\r\n- Sleek CaesarStone kitchen with high end finishes\r\n\r\n- Built-ins to all bedrooms, main with ensuite, walk-through robe\r\n\r\n- Immaculate and as new throughout, ducted air conditioning\r\n\r\n- Remote control blinds, intercom to security entrance\r\n\r\n- Alfresco shutters provide privacy while maintaining view\r\n\r\n- Two secure undercover car spaces, plus additional storage cage\r\n\r\n- Enjoy Marketown amenities; doctors, gym, food and retail\r\n\r\n\r\n\r\nStrata levies $1,355pq',NULL,NULL);
INSERT INTO `listings` VALUES (13616866,'rent','7',NULL,'Snipe Street','Fletcher',2287,'$470','470',3,2,'1',NULL,'This new modern duplex is sure to impress, located within Sanctuary Estate, offering a modern, open plan, spacious and comfortable living experience.\r\n\r\n\r\n- Three bedrooms, each with built-in robes and ceiling fans\r\n\r\n- Separate formal lounge room and study nook\r\n\r\n- Modern kitchen with gas cooking, Split system air conditioning\r\n\r\n- Combined spacious dining and living space\r\n\r\n- Covered outdoor barbecue area and low maintenance backyard\r\n\r\n- Two stylish bathrooms, bathtub to main bathroom\r\n\r\n- Single automatic garage\r\n\r\n- Pets may considered on application\r\n\r\n- Close to popular schools in sought after location',NULL,NULL);
INSERT INTO `listings` VALUES (2015431860,'sale','2',NULL,'Fletcher Street','Adamstown',2289,'$679,950','679950',3,1,'1',NULL,'This deceivingly spacious cottage is full of character and potential. Positioned on a generous corner block in one of Adamstowns most sought-after enclaves. Only minutes to the shops, cafs and local amenities, 15 minutes to the CBD and beaches, inspection is a must.\r\n\r\n\r\n- Elevated corner block\r\n\r\n- Open plan layout with separate living areas\r\n\r\n- High ceilings and polished timber floors throughout\r\n\r\n- Spacious kitchen overlooking the backyard\r\n\r\n- Generous size bedrooms all with built-in robes\r\n\r\n- Large main bathroom with additional shower and second toilet\r\n\r\n- Natural gas points and reverse cycle air conditioning\r\n\r\n- North facing, family-friendly backyard\r\n\r\n- Single garage with internal access\r\n\r\n- Loads of potential in an ideal location',NULL,NULL);
INSERT INTO `listings` VALUES (13724587,'rent','26','E806','Point  Street','Pyrmont',2009,'$680 Per Week','680',1,1,'1',NULL,'Set in the sought-after \'Watermark Plaza\', this spacious one bedroom apartment offers the very best in convenient harbourside living. Its stylishly appointed layout is filled with natural light, custom designed plantation shutters enjoying a pleasant outlook over the streetscape from its elevated Level 8 position with maximum privacy.\r\n\r\nFirst class facilities are available in the complex including 25m indoor pool and full gymnasium. The vibrant attractions of Pyrmont are at your door with Barangaroo and Darling Harbour only moments away. Local attractions include Star City Casino, restaurants & local cafes, harbourside reserves, light rail, ferries & buses at your doorstep with Sydney\'s CBD is easily reached by foot.\r\n\r\n- Private & bright open design lounge and dining area\r\n- Plantation shutters, over sliding glass doors open to balcony\r\n- Smeg kitchen equipped with a gas cooktop, dishwasher and separate pantry\r\n- Generous sized bedroom, mirrored robe, security video intercom and laundry\r\n- Secure car space, full gym and indoor heated pool\r\n- On site manager, a great investment or lock-up and leave\r\n- Close to bike paths, stroll to parks and public transport',NULL,NULL);
INSERT INTO `listings` VALUES (13699580,'rent','4','42','Alexandra  Drive','Camperdown',2050,'$830 Per Week','830',2,2,'1',NULL,'Situated in the \'Aquilon\' building in the sought after City Quarter complex is this luxurious two bedroom stunner offering quality, security & space.\r\n\r\nFeatures Include:\r\n- Sun filled balcony with Sydney City views\r\n- Open plan combined living & dining\r\n- Modern kitchen with ceaser stone benchtop, gas cooking & dishwasher\r\n- Master bedroom with ensuite & built in wardrobe\r\n- Modern bathrooms with quality finishes\r\n- Internal laundry with clothes dryer\r\n- Security building with security intercom system & one security carspace\r\n\r\nCity Quarter development features resort style facilities including a 25m indoor swimming pool and gymnasium plus a second gymnasium and a 50m outdoor lap pool. \r\nWith onsite restaurants, cafe\'s, convenience store & 24 hour security this incredible central location provides the gateway to the Inner West while being only 5 minutes from Sydney CBD and moments from Annandale Village, Royal Prince Alfred Hospital, Glebe, Newtown, Sydney Fish Markets and public transport foot steps away.\r\n\r\nDo not miss the chance to call this apartment home!',NULL,NULL);
INSERT INTO `listings` VALUES (2014369193,'sale','187-191','101','Michael Street','Jesmond',2299,'$445,000  - $495,000','$445000$495000',2,1,'1',NULL,'Si Marco Apartments is a collaboration between multi-award winning Kingston Building Australia and renowned Newcastle Architects SDA, this purpose-built boutique complex of 24 apartments has all the hallmarks of a stylish contemporary lifestyle. Set in the heart of Jesmond, it offers designer living in a central location.\r\n\r\n\r\n- A selection of 2 bedroom apartments over two levels\r\n\r\n- Perfect for owner/occupiers or equally for savvy investors\r\n\r\n- Each apartment features open plan living and outdoor space\r\n\r\n- Features generous proportions and stylish, quality finishes\r\n\r\n- Kitchens feature European styled appliances and stone benchtops\r\n\r\n- NSW Government incentive packages for first home owners\r\n\r\n- Disabled accessible apartment available on ground floor\r\n\r\n- Single security car parking plus a storage cage for each\r\n\r\n- 100m to Stockland Jesmonds array of shops and cafs\r\n\r\n- 1km to University, 3km to John Hunter Hospital, 9km CBD',NULL,NULL);
INSERT INTO `listings` VALUES (13688451,'rent','78',NULL,'Mary Ann Street','Ultimo',2007,'$1100 per week','$1100',3,2,NULL,NULL,'Bursting at the walls with history dating back to the 1860\'s, this Victorian styled terrace provides flourishing streets-cape, a north-facing courtyard and modernized open plan living areas. \r\n\r\nFeatures include: \r\n-	Open plan living areas with French doors leading into a sunny courtyard. \r\n-	Granite gas kitchen with high ceilings. \r\n-	3 double bedrooms, balcony off the main and a very rare attic suite. \r\n-	Freshly designed interiors with an easy to maintain layout\r\n-       Pets upon application\r\n\r\nLocated in the rapidly growing creative district of Ultimo and within walking distance to Sydney\'s iconic Darling Harbour, Sydney CBD and well-known schools and colleges this timeless three-bedroom terrace provides a piece of the past within the present.',NULL,NULL);
INSERT INTO `listings` VALUES (2015842693,'sale','66',NULL,'Fletcher Street','Adamstown',2289,'Auction, price  guide $790,000','790000',3,1,'3','892','This fantastic level site has plenty of options including development potential STCA. The generous flat 892sqm block provides you with the option to renovate and live in the current home, lease out for a good return or you could knockdown to build your dream family home. \r\n\r\n\r\n- Three generous sized bedrooms\r\n\r\n- Double lock-up garage with carport\r\n\r\n- Level block with family-friendly yard\r\n\r\n- In-ground swimming pool\r\n\r\n- Split system air conditioning\r\n\r\n- Close proximity to shops and schools\r\n\r\n- Short walk to public transport\r\n\r\n- Single level garage\r\n\r\n- Good sized block\r\n\r\n- Developments potential STCA',NULL,NULL);
INSERT INTO `listings` VALUES (13697880,'rent','4','2406','Sterling Circuit','Camperdown',2050,'$700 Per Week','700',1,1,'1',NULL,'This contemporary one bedroom loggia apartment is perfectly positioned on level 4 of the \"Vie 2\" building. Set within the award winning City Quarter Community, the apartment is extremely private and features an open plan living and dining areas with abundant natural light and a seamless flow to the 15sqm loggia balcony. \r\n\r\n- One double bedroom featuring walk-through built in robe and private access to the bathroom\r\n- Sleek bathroom with dual access and bathtub\r\n- Contemporary kitchen with European SMEG appliances, dishwasher and gas cooktop\r\n- Internal laundry with dryer and basin\r\n- Split system reverse cycle air conditioning\r\n- Security building with lift and secure car space\r\n- Access to community facilities including indoor & outdoor pools and two gymnasiums\r\n- 24 hour onsite security, cafe, restaurant and convenience store\r\n\r\nOnly 3km to the CBD and an easy stroll to Annandale Village, Glebe and Newtown.\r\n\r\nPlease note this property will be leased unfurnished. Preferred lease term is 12 months.',NULL,NULL);
INSERT INTO `listings` VALUES (13705094,'rent','37/9',NULL,'Hutton Street','Charlestown',2290,'$480','480',3,2,'2',NULL,'Conveniently located within moments of Charlestown Square and magnificent Lake Macquarie, this spacious townhouse is bathed in natural light and offers a contemporary open plan layout and private low maintenance living.\r\n\r\n\r\n- Freshly painted interiors, neutral palette, downlights\r\n\r\n- New timber floors through open plan living/kitchen/dining\r\n\r\n- Private paved courtyard complete with new timber deck\r\n\r\n- Modern kitchen with stainless steel appliances\r\n\r\n- Internal access to remote double lock-up garage with storage\r\n\r\n- Two double bedrooms with ceiling fans and mirrored built-in robes\r\n\r\n- Large master with ceiling fan, study nook, walk-in robe, ensuite\r\n\r\n- Main bathroom with separate bath and shower, gas hot water\r\n\r\n- Separate laundry with new fixtures, third w/c servicing lower level\r\n\r\n- Air conditioning and abundance of storage throughout',NULL,NULL);
INSERT INTO `listings` VALUES (13724095,'rent','20',NULL,'Bottlebrush Boulevard','Fletcher',2287,'$530','530',5,2,'2',NULL,'Would ideally suit all large, growing and extended families. Split level home offering size and space both inside/out. If youre thinking of upsizing and want something big then they dont come much bigger than this. Parents upstairs, kids downstairs or one family upstairs and extended family downstairs, the choice is yours\r\n\r\n\r\n- Five spacious bedrooms with built-in robes, two bathrooms\r\n\r\n- Home office/study, air conditioning, huge underhouse storage\r\n\r\n- Large open plan kitchen, dining room, upstairs lounge room\r\n\r\n- Spacious rear timber deck with elevated local area views\r\n\r\n- Huge downstairs living room and rumpus area\r\n\r\n- Large backyard, 715sqm block approximately\r\n\r\n- Walk to Coles Shopping Centre, minutes from the freeway',NULL,NULL);
INSERT INTO `listings` VALUES (2015229211,'sale','2','9B','Distillery Drive','Pyrmont',2009,'Price Guide contact agent','',2,2,'2',NULL,'Positioned within the stunning \'Silk\' building, architecturally designed by the award winning Tony Caro, this breathtaking two bedroom apartment is a showcase of contemporary luxury with superior quality finishes and unsurpassed Harbour views.\r\n\r\n\r\nEnjoy the spectacular panoramic Harbour and Bridge views from your private vantage point located perfectly on the Northern front of the building.\r\n\r\nThe design elements and inclusions of this luxury residence are exceptional with seamless indoor outdoor integration. Enjoy 143sqm of luminous and private open plan living revealing spotted gum timber floors with full height glass doors extending to the entertainers\' balcony with iconic Harbour backdrop from every room.\r\n\r\n\r\nThere are luxe fully tiled bathrooms and the designer gas kitchen is complimented with European appliances and Caesarstone benchtops perfect for the entertainer.\r\nDesigner features include a backlit gallery wall, integrated study area with built in cabinetry electronic louvres, ducted air and ample storage.\r\n\r\n\r\nDouble security parking and external storage cage complete this property.\r\n\r\nPart of the prestigious Jackson\'s Landing community, it includes resort style facilities, with indoor and outdoor pools, steam room, gyms, tennis courts and 24 hour security. Revel in the lifestyle, a stroll to waterfront restaurants, cafes, parkland, Darling Harbour, the fish markets, Casino and city.\r\n\r\n\r\nWe welcome you to one of the most desirable properties within the area.',NULL,'apartmentUnitFlat');
INSERT INTO `listings` VALUES (13632124,'rent','8','1203','Distillery Drive','Pyrmont',2009,'DEPOSIT TAKEN $1600 per week','$1600',3,2,'1',NULL,'Located in the presidential positioning of the Jacksons Landing development, this tightly held DCM designer building \'Quarry\' has arguably one of the most spectacular views of the iconic Sydney Harbour, both Anzac & Harbour Bridges and city skyline, never to be built out, the best views Pyrmont has to offer. Flooded with light, it showcases high calibre contemporary finishes and a magnificelnt entertainers\' terrace. Private and unbeatably convenient, it\'s a stroll to the light rail, The Star Casino and Pyrmont village. \r\n\r\n- Open plan living, with spectacular north east facing Harbour Bridge and full uninterrupted city views to enjoy both day & night\r\n- Open plan kitchen features a CaesarStone bench top and Smeg gas appliances\r\n- Master bedroom boasts a private semi-enclosed garden balcony, an ensuite and walk-in wardrobe\r\n- The two rear bedrooms have fabulous up-close views over Blackwattle Bay\r\n- Intelligent design incorporates abundant integrated storage, ducted air conditioning & downlights\r\n- Other features include lift access to side by side secure parking, storage & 24hr onsite security\r\n- Resort style facilities include in & outdoor pools, two gyms, a tennis court and community hall\r\n\r\nCHOICE OF PARTIALLY FURNISHED or UNFURNISHED',NULL,'apartmentUnitFlat');
INSERT INTO `listings` VALUES (2014438842,'sale','9-15','21','Cherry Street','Warrawee',2074,'$1,598,000','$1598000',4,3,'2',NULL,'First Open Home This Weekend!\r\n\r\nView our new display home styled by Coco Republic\r\n\r\nBeautiful homes in a cherished North facing location. Nestled in Warrawee\'s leafy heart, Cherry Street Residences blend the appeal of a house with the luxurious comforts and convenience of a large spacious apartment. Enjoy living in the suburb\'s finest street, with seamless light-filled spaces designed for relaxing, entertaining and easy family life. Lush private garden courtyards flow from open plan living areas, bringing the outside in. Premium natural finishes, exceptional detailing and abundant storage offer timeless elegance and a practical sense of home.\r\n\r\n- Beautiful and spacious floor plans with large living areas seamlessly flowing to outside areas and large bedrooms\r\n- High quality finishes including European appliances, stone bench and vanity tops and engineered timber floors\r\n- All homes with three to four bathrooms plus powder rooms\r\n- Luxurious full floor main bedroom floorplans available\r\n- Generous free flowing design by renowned Connor + Solomon Architects \r\n- A beautifully quiet serene location close to everything the North Shore has to offer\r\n- Boutique collection of individual townhouses assuring privacy, security and low maintenance\r\n- Less than 500m level walk to train station and close to Sydney\'s best schools and universities\r\n- Australian development group with strong track record of previous developments\r\n\r\nArrange your VIP viewing of our new display home styled by Coco Republic. Call Noel Lucas-Martinez 0411 175 506',NULL,NULL);
INSERT INTO `listings` VALUES (13632321,'rent','137','32','Bayswater Road','Rushcutters Bay',2011,'DEPOSIT TAKEN $670 per week','$670',1,1,'1',NULL,'Positioned amongst Sydney\'s most vibrant areas, this stunning Bayswater Apartment presents a unique opportunity for executives to reside in a near new, contemporary low-maintenance apartment in the centre of Sydney\'s\r\ninner east.\r\n\r\nFeaturing:\r\n- Spacious interiors and clever design by award winning architects Candalepas Associates\r\n- Huge north facing enclosed winter garden balcony\r\n- District and area views\r\n- European oak timber floors throughout\r\n- Boutique low maintenance building\r\n- Fully ducted reverse cycle air-conditioning \r\n- Contemporary and sleek bathroom\r\n\r\nPerfectly positioned in the heart of Sydney\'s inner east, short walk to Edgecliff and Kings Cross train stations, Rushcutters Bay Park, restaurants, bars and fresh food providers.',NULL,'apartmentUnitFlat');
INSERT INTO `listings` VALUES (13676908,'rent','40','901','Refinery Drive','Pyrmont',2009,'$1700 per week','$1700',3,2,'2',NULL,'This iconic property is the most sought after three bedroom apartment in the exclusive Jacksons Landing estate. Set on the top level (9) with uninterrupted water views and complete privacy, this apartment is sure to impress.  \r\n\r\nFeatures:\r\n- Custom timber flooring throughout\r\n- Renovated property with custom made additions throughout\r\n- Stunning direct water views with Harbour Bridge & Barangaroo backdrop\r\n- Huge floor plan with large living & dining area boasting a North aspect\r\n- Sleek stainless steel kitchen with gas appliances and casual dining area\r\n- Large balcony, perfect for entertaining family & friends\r\n- King-sized private master retreat with deluxe marble ensuite and walk-through robe\r\n- Double-sized second bedroom with built-in wardrobe\r\n- Internal laundry and video intercom\r\n- Two secure side-by-side car spaces and direct lift access\r\n\r\nSituated in the premiere Jacksons Landing Estate, you\'ll enjoy resort facilities including heated indoor pool, gym, sauna and tennis courts. Located on the water\'s edge, and no more than a short walk to restaurants, cafes and The Star casino and CBD.',NULL,NULL);
INSERT INTO `listings` VALUES (2014438841,'sale','9-15','19','Cherry Street','Warrawee',2074,'$1,995,000','$1995000',4,3,'2',NULL,'First Open Home This Weekend!\r\n\r\nView our new display home styled by Coco Republic\r\n\r\nBeautiful homes in a cherished North facing location. Nestled in Warrawee\'s leafy heart, Cherry Street Residences blend the appeal of a house with the luxurious comforts and convenience of a large spacious apartment. Enjoy living in the suburb\'s finest street, with seamless light-filled spaces designed for relaxing, entertaining and easy family life. Lush private garden courtyards flow from open plan living areas, bringing the outside in. Premium natural finishes, exceptional detailing and abundant storage offer timeless elegance and a practical sense of home.\r\n\r\n- Beautiful and spacious floor plans with large living areas seamlessly flowing to outside areas and large bedrooms\r\n- High quality finishes including European appliances, stone bench and vanity tops and engineered timber floors\r\n- All homes with three to four bathrooms plus powder rooms\r\n- Luxurious full floor main bedroom floorplans available\r\n- Generous free flowing design by renowned Connor + Solomon Architects \r\n- A beautifully quiet serene location close to everything the North Shore has to offer\r\n- Boutique collection of individual townhouses assuring privacy, security and low maintenance\r\n- Less than 500m level walk to train station and close to Sydney\'s best schools and universities\r\n- Australian development group with strong track record of previous developments\r\n\r\nArrange your VIP viewing of our new display home styled by Coco Republic.\r\n\r\nCall Noel Lucas-Martinez 0411 175 506',NULL,'townhouse');
INSERT INTO `listings` VALUES (13652384,'rent','6-8','303','Mount Street Walk','Pyrmont',2009,'$1,000 per week','$1000',2,2,'1',NULL,'The Rum Store, circa 1879, reflects Sydney\'s colonial past during an industrial era. The intimate complex has just 13 unique residences. This tasteful warehouse conversion offers a unique two bedroom apartment with original iron-bark timber beams, sandstone window sills.\r\n\r\n- Luxury two bedroom warehouse conversion living\r\n- High ceilings with timber roofing\r\n- Cast iron columns, hardwood beams and cast iron windows\r\n- Gourmet stainless steel kitchen with granite and timber finishes\r\n- Two bathrooms with high quality finish\r\n- Resort style facilities, pool, gym, tennis courts and function hall\r\n- 24 hour onsite security\r\n- Split-System Air- conditioning in master bedroom & lounge room\r\n\r\nRelaxed yet sophisticated, refined and intriguing, The Rum Store is as unique as the individuals who choose to live there. A rare opportunity to live in a piece of history which complements the unique characteristics of a bye gone era with today\'s modern lifestyle essentials.',NULL,NULL);
INSERT INTO `listings` VALUES (13609743,'rent','261','803','Harris Street','Pyrmont',2009,'DEPOSIT TAKEN','',3,2,'2',NULL,'Commanding city skyline and district views from three luxurious levels at the top of the renowned \'Pyrmont Court\' building, this renovated 3 bedroom promises an ideal city fringe lifestyle. It\'s footsteps to cafÃ©s, buses, The Star and Darling Harbour.\r\n\r\nFeatures:\r\n- Open plan living and dining with polished timber floorboards\r\n- Three bedrooms with built-in wardrobes, ensuite to master\r\n- Outdoor flow to a city view balcony for alfresco entertaining\r\n- Private rooftop terrace on title with 220 degree panorama\r\n- Fresh paint throughout, new LED lighting, new blinds throughout\r\n- 3rd toilet (powder room) & internal laundry \r\n- Pets upon application\r\n\r\nOn site leisure facilities include gym, pool, spa and sauna with a Building manager, secure double car space, air conditioning in each room & the ultimate convenience with only a short walk to all the CBD has to offer.',NULL,'apartmentUnitFlat');
/*!40000 ALTER TABLE `listings` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2019-11-16 22:08:02
